new_weapon_for_sec
space-exodus/space-station-14 pull request #51
Opened 2024-07-30 01:59 UTC by unDepresh

Убрано табельный mk-58 у таких ролей как: Офицер сб, смотритель, ГСБ.
Добавлен миниатюрный энергетический пистолет как табельное оружие офицеру сб и смотрителю, так за 2500 можно заказать ящик с двумя такими. 
Добавлен Х-2 Двухфазовый энергетический лазерный пистолет. Появляется у ГСБ как табельное оружие в кармане
Removed the mk-58 from such roles as: Officer of the sb, caretaker, GSB.
Added a miniature energy pistol as a tactical weapon for the sec officer and warden, so for 2500 you can order a box with two of them. 
Added X-2 Dual Phase Energy Laser Pistol. Appears in the HoS as a service weapon in his pocket

2024-07-30 01:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/space-exodus/space-station-14?pullRequest=51) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/space-exodus/space-station-14?pullRequest=51) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/space-exodus/space-station-14?pullRequest=51) it.</sub>

2024-07-30 10:06 UTC, Fragoler requested changes
Необходимо немного подправить общий вид PR.

2024-07-30 10:06 UTC, Fragoler commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/MyltiLaserForHoS.yml
> +- type: entity
Переместить в Exodus/Entities/Objects/Weapons/Guns/Projectiles/

2024-07-30 10:06 UTC, Fragoler commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/MyltiLaserForHoS.yml
> +- type: entity
Переместить в Exodus/Entities/Objects/Weapons/Guns/Projectiles/

2024-07-30 10:06 UTC, Fragoler commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/MyltiLaserForHoS.yml
> +- type: entity
Переместить в Exodus/Entities/Objects/Weapons/ Effects?..

2024-07-30 10:06 UTC, Fragoler commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/MyltiLaserForHoS.yml
> +- type: entity
Переместить в Exodus/Entities/Objects/Weapons/ Effects?..

2024-07-30 10:06 UTC, Fragoler commented on Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
> -    pocket1: WeaponPistolMk58
Комментарий изменения кода оффов

2024-07-30 10:06 UTC, Fragoler commented on Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
> -    pocket1: WeaponPistolMk58
Комментарий изменения кода оффов

2024-07-30 10:06 UTC, Fragoler commented on Resources/Prototypes/Roles/Jobs/Security/warden.yml
> -    pocket1: WeaponPistolMk58
Комментарий изменения кода оффов

2024-07-30 10:06 UTC, Fragoler commented on Resources/Textures/Objects/Weapons/Guns/Battery/MyltiLaserForHoS.rsi/meta.json
> +{
Разделить на смысловые части. 
Переместить в Textures/Exodus/
Разделить на rsi

2024-07-30 10:06 UTC, Fragoler commented on Resources/Audio/Weapons/HoSLaser.ogg
Переместить в Audio/Exodus/

2024-07-30 10:06 UTC, Fragoler commented on Resources/Audio/Weapons/MiniEnergyGun.ogg
Переместить в Audio/Exodus/

2024-07-30 10:06 UTC, Fragoler commented on Resources/Audio/Weapons/HoSLaser.ogg
Написать Atttribution.yml для звуков

2024-07-30 12:25 UTC, Lokilife commented
Заменить текстурки самих лазеров на обесцвеченные (спойлер, одна из них уже есть) и задавать цвет уже в компоненте Sprite.

2024-07-30 12:36 UTC, unDepresh commented
> Заменить текстурки самих лазеров на обесцвеченные (спойлер, одна из них уже есть) и задавать цвет уже в компоненте Sprite.
А зачем вообще и в какой из них уже такая обесцвеченная есть? Я с текстурами пока особо не работал нормально, но этот момент у тебя в коде лазера осщ видел

2024-08-30 10:27 UTC, Fragoler reviewed
Переименовать, разрешить конфликт, да понять что-то с дробовиком и будет конфетка..)

2024-08-30 10:27 UTC, Fragoler commented on Resources/Textures/Exodus/Objects/Weapons/Guns/Projectiles/ProjectilesForLaserByDepresh.rsi/meta.json
> +{
Переименовать папку...

2024-08-30 10:27 UTC, Fragoler commented on Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
> +    pocket1: WeaponMiniEnergyGun # Убрал "WeaponPistolMk58" и добавил "WeaponMiniEnergyGun"
Заменить на комментарий # Exodus - WeaponForHos

2024-08-30 10:27 UTC, Fragoler commented on Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
> +    back: # Убрал "MagazinePistol "
Заменить комментарий

2024-08-30 10:27 UTC, Fragoler commented on Resources/Prototypes/Roles/Jobs/Security/warden.yml
> +    pocket1: WeaponMiniEnergyGun # Убрал "WeaponPistolMk58" и добавил "WeaponMiniEnergyGun"
Заменить комментарий

2024-08-30 10:27 UTC, Fragoler commented on Resources/Prototypes/Roles/Jobs/Security/warden.yml
> +    back: # Убрал "MagazinePistol"
Заменить комментарий

2024-08-30 10:27 UTC, Fragoler commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Projectiles/ProjectilesForLaserForHos.yml
> +# проджект лазера
Заменить название файла на LaserForHos.yml

2024-08-30 10:27 UTC, Fragoler commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Projectiles/ProjectilesForMiniEnergyGun.yml
> +# продект лазера
Заменить название на MiniEnergyGun.yml

2024-08-30 10:27 UTC, Fragoler commented on Resources/Prototypes/Exodus/Catalog/Fills/Crates/securityWithEnergyGunForSec.yml
> +- type: entity
Заменить название файла на security.yml

2024-08-30 10:27 UTC, Fragoler commented on Resources/Prototypes/Exodus/Catalog/Cargo/cargo_securityWithMiniEnergyGun.yml
> +- type: cargoProduct
Заменить название файла на security.yml

2024-08-30 12:09 UTC, Lokilife commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Projectiles/ProjectilesForLaserForHos.yml
> +# проджект лазера
:x:
На `energetic.yml`, если файл уже существует, то закинуть в конец. Исправить косяки с опечатками. Нет такого слова Staner, есть Stunner, от слова Stun. И всё в таком духе.
Также эффекты от попаданий лежат во отдельном файле, `impacts.yml`

2024-08-30 12:10 UTC, Lokilife commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Projectiles/ProjectilesForMiniEnergyGun.yml
> +# продект лазера
К `projectiles.yml`, эффекты от попаданий в `impacts.yml`

2024-08-30 12:11 UTC, Lokilife commented on Resources/Textures/Exodus/Objects/Weapons/Guns/Projectiles/ProjectilesForLaserByDepresh.rsi/meta.json
> +{
На кой чёрт этот RSI, если в сборке такие спрайты уже есть?

2024-08-30 12:12 UTC, Lokilife commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Projectiles/ProjectilesForLaserForHos.yml
> +  id: stanerBullet
Здесь вообще нарушение конвенции имён энтитей, которые должны быть в PascalCase (начинается с большой буквы и каждое слово тоже с большой)

2024-08-30 12:13 UTC, Lokilife commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Projectiles/ProjectilesForMiniEnergyGun.yml
> +  id: BulletImpactEffectLaserStan
`BulletImpactEffectLaserCyan` -> `BulletImpactEffectStunnerCyan`

2024-08-30 12:13 UTC, Lokilife commented on Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
> +    pocket1: WeaponPistolMk58
Потерял коментарий

2024-08-30 12:15 UTC, Lokilife commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Projectiles/ProjectilesForMiniEnergyGun.yml
> +  id: LaserBulletForMEG
Никаких "AForB" в ID и названиях. -> `LaserBulletMEG`.

2024-08-30 12:16 UTC, Lokilife commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Battery/MiniEnergyGunForSec.yml
> +  name: Mini energy gun
Название энтити с маленькой буквы быть должны

2024-08-30 12:16 UTC, Lokilife commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Battery/MiniEnergyGunForSec.yml
> +  name: Mini energy gun
Да и название по-креативнее бы....

2024-08-30 12:18 UTC, Lokilife commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Projectiles/ProjectilesForMiniEnergyGun.yml
> +  id: LaserBulletForMEG
А ещё лучше отнести снаряд лазера к какой-либо категории, более унифицированно и отталкиваться уже от названия категории, а не от названия пушки, для которой он был сделан.

2024-08-30 12:20 UTC, Lokilife commented on Resources/Prototypes/Exodus/Entities/Objects/Weapons/Guns/Projectiles/ProjectilesForLaserForHos.yml
> +  id: BulletImpactEffectDisablerRed
Ну хоть себе-то не ври.
`BulletImpactEffectDisablerRed` -> `BulletImpactEffectDisablerPink`

2024-08-30 12:21 UTC, Lokilife commented
С названиями сплошная лажа.
@Fragoler внимательнее следи за кодом, который проверяешь и одобряешь.

2024-11-26 21:17 UTC, closed without merging

2024-11-26 21:17 UTC, unDepresh commented
Мне в падлу это допиливать