20.08.2024 fix pointsmap and brigmed | FIX
space-exodus/space-station-14 pull request #61
Opened 2024-08-20 00:27 UTC by CrimeMoot

## Описание PR
1. **Добавлены новые тесты:**
   - **`GameMapsLoadableTest`**: Проверяет, что игровые карты загружаются корректно и что все доступные рабочие места имеют соответствующие точки появления на картах. Если таких нет, покажет ошибку: Должность которая не получила спавн - до этого, была просто ошибка без демонстрации с причиной Null и самой карты.
   - **`NonGameMapsLoadableTest`**: Проверяет загрузку неигровых карт, чтобы убедиться, что они загружаются без ошибок.

2. **Улучшены существующие тесты:**
   - **`GridsLoadableTest`**:  тестовые карты загружаются как сетки, а не карты.
   - **`NoSavedPostMapInitTest`**: Проверяет, что карты не сохранены с включенным `postmapinit`.

3. **Вывод информации о рабочих местах:**
   - В тесте `GameMapsLoadableTest` добавлены выводы информации о точках появления и доступных рабочих местах для лучшего понимания состояния карт.
   
4. **Временно убрана должность Бригмедик с карты.**
   - **`Бригмедик`**: временно удалён с карт:  **[exodus_cluster.yml](https://github.com/CrimeMoot/CCmoot/pull/3/commits/f4e146066c39ac9136ae2821af1039fb71797653#diff-a8982e8ba59647d88d3e156206b5120ce74886c4ad1b545e9762ea1ab0054e8a)** and **[exodus_saltern.yml](https://github.com/CrimeMoot/CCmoot/pull/3/commits/b0c74f99b492f72748299ea70a35301af01e6e86#diff-894dec2b3b2a2833190e14ff91ddf3c9c467e9d1528d2338a3be95944f39871a)**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl: Matheamt1ka
- add: Добавлены новые тесты.
- add: Вывод информации о рабочих местах.
- remove: Бригмедик убран до исправление карты спавна.
- tweak: Улучшены существующие тесты.
- tweak: Null больше не показывается.

2024-08-20 00:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/space-exodus/space-station-14?pullRequest=61) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/space-exodus/space-station-14?pullRequest=61) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/space-exodus/space-station-14?pullRequest=61) it.</sub>

2024-08-20 00:30 UTC, CrimeMoot commented
Впрочем.
Как спавны для БМ сделайте. Ошибку больше не будет. А в целом пригодиться на будущее, если забыли спавны. 🐩

2024-08-20 01:40 UTC, CrimeMoot commented
# **green test** :)

2024-08-20 05:52 UTC, Fragoler requested changes
Оффовские тесты, их мало кто тыкает моё почтение. Разрешите пару маленьких вопросов и все будет отлично

2024-08-20 05:52 UTC, Fragoler commented on Content.IntegrationTests/Tests/PostMapInitTest.cs
> -                || xform.GridUid == null
Табуляции вне комментария изменения...

2024-08-20 05:52 UTC, Fragoler commented on Resources/Prototypes/Exodus/Entities/Structures/Decoration/arcs.yml
> +#  abstract: true  // can ?
С какой целью это было сделано?

2024-08-20 10:17 UTC, CrimeMoot commented on Resources/Prototypes/Exodus/Entities/Structures/Decoration/arcs.yml
> +#  abstract: true  // can ?
А что это вообще?
Что за объект. Он разве не как скрытый должен быть?

2024-08-20 10:20 UTC, CrimeMoot commented on Resources/Prototypes/Exodus/Entities/Structures/Decoration/arcs.yml
> +#  abstract: true  // can ?
> С какой целью это было сделано?
Я считал т.к это база - просто родитель для других объектов.
Т.к те вне зависимости от ёBaseDungeonArcё меняли `Physics` -даже если указано в нём самом обратное.

2024-08-20 10:30 UTC, CrimeMoot commented on Resources/Prototypes/Exodus/Entities/Structures/Decoration/arcs.yml
> +#  abstract: true  // can ?
По больше части я его менял только чтоб Тесты не мешали.
Т.к тест не ожидает изменение `Physics`. потому что они отличаются от того что указано `BaseDungeonArc`  по этому и выдаёт ошибку. Не люблю крестик на проверках :(

2024-08-20 10:51 UTC, CrimeMoot commented on Content.IntegrationTests/Tests/PostMapInitTest.cs
> -                || xform.GridUid == null
![1226231640091791451](https://github.com/user-attachments/assets/3c07679c-2f2e-480c-a131-8030f94aadbd)

2024-08-20 10:59 UTC, CrimeMoot commented on Content.IntegrationTests/Tests/PostMapInitTest.cs
> -                || xform.GridUid == null
> Табуляции вне комментария изменения...

Так там нет изменений. Я даже это не менял. Это сам редактор поменял, на две клетки сместил. Оно ничего не поменяет.

2024-08-22 05:43 UTC, Fragoler commented
В пн проверю арки

2024-08-26 16:58 UTC, merged